config/routes.rb
QrMendeley::Application.routes.draw do

  resources :posters,
            :except => :destroy     # Need to implement this for admins

  match "about" => 'home#about'

  root :to => 'home#index'

end

app/models/affiliation.rb
# == Schema Information
# Schema version: 20110611202518
#
# Table name: affiliations
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)     not null
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_affiliations_on_name  (name) UNIQUE
#

class Affiliation < ActiveRecord::Base

  include DatabaseValidation

end

app/models/author.rb
# == Schema Information
# Schema version: 20110611202518
#
# Table name: authors
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)     not null
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_authors_on_name  (name) UNIQUE
#

class Author < ActiveRecord::Base

  include DatabaseValidation

  has_many :poster_authors

  has_many :posters,
            :through => :poster_authors

end

app/models/event.rb
# == Schema Information
# Schema version: 20110611202518
#
# Table name: events
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)     default("0")
#  start_date :datetime        not null
#  event_date :datetime        not null
#  location   :string(255)
#  homepage   :string(255)
#  hashtag    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Event < ActiveRecord::Base

  include DatabaseValidation

  validates :homepage,
            :url => { :allow_blank => true }
  
end

app/models/poster.rb
# == Schema Information
# Schema version: 20110611202518
#
# Table name: posters
#
#  id         :integer(4)      not null, primary key
#  title      :string(255)     not null
#  abstract   :text            default(""), not null
#  event_id   :integer(4)
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_posters_on_event_id  (event_id)
#

class Poster < ActiveRecord::Base

  include DatabaseValidation

  belongs_to :event

  has_many :poster_authors,
            :dependent => :destroy

  accepts_nested_attributes_for :event

end

app/models/poster_author.rb
# == Schema Information
# Schema version: 20110611202518
#
# Table name: poster_authors
#
#  id             :integer(4)      not null, primary key
#  poster_id      :integer(4)      not null
#  author_id      :integer(4)      not null
#  affiliation_id :integer(4)      not null
#  created_at     :datetime
#  updated_at     :datetime
#
# Indexes
#
#  poster_authors_ids_index           (poster_id,author_id) UNIQUE
#  index_poster_authors_on_poster_id  (poster_id)
#

class PosterAuthor < ActiveRecord::Base

  include DatabaseValidation

  belongs_to :poster

  belongs_to :author

  belongs_to :affiliation

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
  def about
  end

end

app/controllers/posters_controller.rb
class PostersController < ApplicationController

  # GET /posters
  # GET /posters.xml
  def index
    @posters = Poster.all
  end

  # GET /posters/1
  # GET /posters/1.xml
  def show
    @poster = Poster.find(params[:id])
  end

  # GET /posters/new
  # GET /posters/new.xml
  def new
    @poster = Poster.new
  end

  # GET /posters/1/edit
  def edit
    @poster = Poster.find(params[:id])
  end

  # POST /posters
  # POST /posters.xml
  def create
    @poster = Poster.new(params[:poster])

    if @poster.save
      redirect_to(@poster, :notice => 'Poster was successfully registered.')
    else
      render :action => "new"
    end
  end

  # PUT /posters/1
  # PUT /posters/1.xml
  def update
    @poster = Poster.find(params[:id])

    if @poster.update_attributes(params[:poster])
      redirect_to(@poster, :notice => 'Poster was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /posters/1
  # DELETE /posters/1.xml
  def destroy
    @poster = Poster.find(params[:id])
    @poster.destroy

    redirect_to(posters_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include TweetButton

  def title(page_title, options={}, &block)
    content_for(:title, page_title.to_s)
    content_tag(:div, 'data-role' => 'header', 'data-backbtn' => 'false') do
      if block_given?
        concat(capture(&block))
      else
        concat(content_tag(:h1, page_title, options))
      end
      concat(link_to("Home", root_path, :class => "ui-btn-right", "data-icon" => "home"))
    end
  end

  def content(&block)
    content_tag(:div, 'data-role' => 'content') do
      concat(render :partial => 'layouts/messages')
      concat(capture(&block))
    end
  end

  def footer(&block)
    content_tag(:div, 'data-role' => 'footer') do
      capture(&block)
    end
  end

  def button(content_for_button, link, options={})
    options.reverse_merge!({
      'data-role' => 'button'
    })

    link_to(content_for_button, link, options)
  end

  def qr_code_image_tag(url)
    image_tag "http://chart.apis.google.com/chart?chs=200x200&cht=qr&&chld=H&chl=#{url}"
    
  end
  
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/views/home/about.html.haml
= title 'About Team Sabaku'

= content do
  %ul{'data-role'=>"listview", 'data-inset'=>"true" }
    %li{'data-role'=>"list-divider"}
      Team
    %li
      Jiten Bhagat
    %li
      Kees Burger
    %li
      Helena Deus
    %li
      Alvaro Graves
    %li
      Andra Waagmeester

app/views/home/index.html.haml
= title 'QRMendeley'

= content do
  %ul{ 'data-role'=>"listview", 'data-inset'=>"true" }
    %li{ 'data-role'=>"list-divider" }
      Main Menu
    %li
      = link_to "All Posters", posters_path
    %li
      = link_to "Register a Poster", new_poster_path
    %li
      = link_to "About Us", about_path

app/views/layouts/_footer.html.haml
= footer do
  %p.copyright_text
    &copy; 2011 - Team Sabaku

app/views/layouts/_head_title.html.haml
%title
  = content_for(:title)
  -
  = Settings.site.name

app/views/layouts/_messages.html.haml
- if flash[:notice]
  %div#flash_notice{:class => "flasher"}= flash[:notice]
- if flash[:error] || flash[:failure] || flash[:alert]
  %div#flash_failure{:class => "flasher"}= flash[:error] || flash[:failure] || flash[:alert]
- if flash[:success]
  %div#flash_success{:class => "flasher"}= flash[:success]

app/views/layouts/application.html.haml
!!! 5
-# paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
%html.no-js{ :lang => "en" }
  <!--<![endif]-->
  %head
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html; charset=utf-8'}
    %meta{'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'}   
    = render :partial => "layouts/head_title"
    %meta{:name => 'description', :content => ''}
    %meta{:name => 'author', :content => ''}
    %meta{:name => 'viewport', :content => 'width=device-width initial-scale=1.0 maximum-scale=1.0'}
    %meta{:name => 'apple-mobile-web-app-capable', :content => 'yes'}
    = csrf_meta_tag
    = include_stylesheets :app, :media => 'all'
    = include_javascripts :app
    = yield(:head)
  %body
    %div{ 'data-role' => 'page', 'data-theme' => "b", 'data-dividertheme' => "c" }
      = yield
      = render :partial => "layouts/footer"

app/views/posters/_form.html.haml
.ui-body.ui-body-c{ 'data-theme' => 'c' }
  = form_for @poster, :html => { 'data-ajax' => 'false' } do |f|
    #title_field{ 'data-role' => 'fieldcontain' }
      = f.label :title, 'Title*'
      = f.text_field :title
    #abstract_field{ 'data-role' => 'fieldcontain' }
      = f.label :abstract, 'Abstract*'
      = f.text_area :abstract, :style => 'height: 10em;'
    #abstract_field{ 'data-role' => 'fieldcontain' }
      = f.label :download_url, 'Download URL*'
      = f.text_field :download_url
    %fieldset.ui-grid-a
      %div.ui-block-a
        = submit_tag "Cancel", 'data-theme' => 'c'
      %div.ui-block-b
        = f.submit nil, 'data-theme' => 'b'

app/views/posters/edit.html.haml
%h1 Editing poster

= render 'form'

= link_to 'Show', @poster
\|
= link_to 'Back', posters_path

app/views/posters/index.html.haml
= title "All Posters"

= content do

  - if @posters.empty?
    %p.center No posters yet
  - else
    %ul{ 'data-role'=>"listview", 'data-inset'=>"true" }
      - @posters.each do |poster|
        %li
          = link_to poster do
            %h2= poster.title
            %p= truncate(poster.abstract, :length => 50)

  %p= button 'Register a Poster', new_poster_path, "data-icon" => "plus", "class" => "ui-btn-right"

app/views/posters/new.html.haml
= title "Register a Poster"

= content do
  = render 'form'
  %p= button "View all Posters", posters_path

app/views/posters/show.html.haml
= title "Poster - #{@poster.title}"

= content do

  .spread
   
    = link_to("Tweet", "http://twitter.com/share", "data-count" => "horizontal", "data-via" => "qrmendeley", :class => "twitter-share-button left")
  
  .mendeleyLink
  
    = link_to(image_tag("importMendeley.gif"), "http://www.mendeley.com/import?url=http://qrmendeley.me"+request.path)

   
    %script{:src => "http://platform.twitter.com/widgets.js", :type => "text/javascript"}
    
    %span.Z3988{:title => "ctx_ver=Z39.88-2004&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rfr_id=info%3Asid%2Focoins.info%3Agenerator&rft.genre=article&rft.atitle=Article&rft.title=Conference+of+conferences&rft.date=2011-03-06&rft.aulast=LAuthor1&rft.aufirst=FAuthor1&rft.au=FAuthor1+LAuthor1&rft.au=FAuthor2+LAuthor2&rft.au=FAuthor3+LAuthor3"}

  %h4 Abstract
  .abstract
    = simple_format @poster.abstract

  %h4 Download URL
  .download_url
    = link_to @poster.download_url, @poster.download_url, :popup => true

  %h4 QR Code
  = qr_code_image_tag poster_url(@poster)
  %h5 Scan me to add to Mendeley and tweet about this poster
 

  %p= button "View all Posters", posters_path
  

 
 